### ISSUE TITLE
App Design Definition - Create Sketch of Loading Screen

### ISSUE THREAD

**Issue by fmacmahon** [RomaoFilipe/appDAMA#5]
This task involves designing the loading screen for a billiards lesson scheduling app. It includes creating a detailed sketch that illustrates the layout and visual elements. The loading screen will feature the app's logo or icon prominently, along with a progress indicator such as a spinner or progress bar to inform users that the app is loading. The design will ensure a visually appealing and engaging experience, providing users with a smooth transition as the app initializes. This screen sets the stage for the app's overall design consistency and user experience.

**Comment by RomaoFilipe** [comment]
Design draft created.

![Image](https://github.com/RomaoFilipe/appDAMA/assets/150187169/d2a88a05-1abb-4fc4-ba8b-bd6451c1d9ce)
