### ISSUE TITLE
App Design Definition - Create Sketch of Scheduling Screen

### ISSUE THREAD

**Issue by fmacmahon** [RomaoFilipe/appDAMA#6]
This task involves designing the scheduling screen for a billiards lesson scheduling app. It includes creating a detailed sketch that outlines the layout, user interface elements, and user experience flow. The scheduling screen will feature:

- Date Picker: Allows users to select the desired date for their billiards lesson.
- Time Slots: Displays available time slots for the selected date, enabling users to choose a convenient time.
- Instructor Selection: Option to select a preferred instructor from a list.
- Confirmation Button: A button to confirm and schedule the lesson.
- Back/Cancel Button: An option to return to the previous screen or cancel the scheduling process.
- Summary Section: Provides a brief summary of the selected date, time, and instructor before final confirmation.

The design aims to be straightforward and user-friendly, making it easy for users to schedule lessons quickly and efficiently. The layout will prioritize clarity and ease of use, ensuring a seamless scheduling experience.

**Comment by RomaoFilipe** [comment]
Design draft created.

![Image](https://github.com/RomaoFilipe/appDAMA/assets/150187169/a27f0abe-83be-4b27-99db-215a89e54bdb)
