### ISSUE TITLE
App Design Definition - Create Sketch of Main Screen

### ISSUE THREAD

**Issue by fmacmahon** [RomaoFilipe/appDAMA#7]
This task involves designing the main screen for a billiards lesson scheduling app. It includes creating a detailed sketch that outlines the layout, user interface elements, and user experience flow. The design aims to be user-friendly and efficient, ensuring that users can easily manage their billiards lessons with minimal effort. The layout will be intuitive, prioritizing accessibility and a seamless user experience.

**Comment by RomaoFilipe** [comment]
Design draft created.

![Image](https://github.com/RomaoFilipe/appDAMA/assets/150187169/f7845c16-5530-45fa-bd06-4cc32468be66)
